version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - ./backend/todo/.env
  backend:
    build:
      context: ./backend
    command:  gunicorn todo.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_started
  frontend:
    build:
      context: ./frontend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code
      - /code/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_started