version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - ./backend/todo/.env
  web:
    build:
      context: ./backend
    command:  gunicorn todo.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_started