version: "3.9"

services:
  web:
    build:
      context: ./backend
    command:  gunicorn todo.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000